### ISSUE TITLE
clarification: Phase-1.1 阻止更小的 State 被 commit

### ISSUE THREAD

**Issue by andypeng2015** [openacid/abstract-paxos#5]
```
每个 node 在 P1Reply 中返回自己之前保存的 commit_index, writer 拿到 reply 后跟自己的commit_index 对比, 如果 w.commit_index >= P1Reply.commit_index, 表示 phase-1.1 成功.
```
感谢分享，受益

请教 这里有一个疑问 如果是 `如果 w.commit_index >= P1Reply.commit_index` 两个writer commit_index 一样大 会同时进入Phase2，造成值被覆盖？

这里 应该是 `如果 w.commit_index > P1Reply.commit_index` 吗？

感谢

**Comment by drmingdrmer** [comment]
等于是因为可能是重复的P1Request被发了出去, 第二次收到时,返回的P1Reply.commit_index就是跟writer的相等了

**Comment by andypeng2015** [comment]
> 等于是因为可能是重复的P1Request被发了出去, 第二次收到时,返回的P1Reply.commit_index就是跟writer的相等了

谢谢 前提是两个writer 生成的commit_index唯一且单调增？

**Comment by drmingdrmer** [comment]
是的, 这个必须要保证, paxos里是`rnd=(int, node_id)`是这个commit_index, raft里是`(term, voted_for)`对应commit_index
